### ISSUE TITLE
Map変更画面の確定ボタンが反応しない

### ISSUE THREAD

**Issue by daicyan** [HillTopTRPG/quoridorn-vue-cli-3#1]
「マップ」→「マップ変更」→「適当な画像を選択」→「確定」を反応がない。

そのまま他の利用者がログインするか他の利用者がブラウザをリロードするとマップは変わっているけど、キャンセルやマップ変更画面を×で閉じると、「確定」を一度推しているのも関わらず元に戻ってしまうため、変更後の状態を維持したままマップ変更画面を閉じることが出来ない。

確認バージョン：1.0.0b7, 1.0.0b8
サーバー：Quoridorn公式鯖
仕様ブラウザ：GoogleChromeおよびVivaldi

**Comment by HillTopTRPG** [comment]
再現性を確認し、対応させていただきました。
ご報告ありがとうございます。
1.0.0b8.1にて改善しております。
